import Head from "next/head";
import { Inter } from "next/font/google";
import Banner from "../../components/home/banner";
import About from "../../components/home/about";
import About_Category from "../../components/home/about_category";
import WhyChoose from "../../components/home/why-choose";
import Team from "../../components/home/team";
import OfficeStructure from "../../components/home/office-structure";
import Testimonial from "../../components/home/testimonial";
import Overview from "../../components/home/overview";
import Blog from "../../components/home/blog";
import Newsletter from "../../components/home/newsletter";
import { axiosGet } from "../../utils/ApiCalls";
import { useEffect } from "react";
import HomeModal from "../../components/home/HomeModal";



export default function Home({data}) {
  // const { home_banners = [], home_contents = {} } = data || {};
  return (
    <>
      <Head>
        <title>Egrassrooter</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      
      <main>

        <Banner banners={data.home_banners}/>
        <About about={data.home_contents} />
        <About_Category aboutservices={data.services}/>
        <WhyChoose whychoose={data.home_contents} />
        <Team teamData={data.latest_parties}/>
        <OfficeStructure offStructures={data.home_contents} OffFeatures={data.features} />
        <Testimonial Testimonials={data.testimonials}/>
        <Overview overview={data.home_contents}/>
        <Blog />
        <Newsletter />
        <HomeModal/>
      </main>
    </>
  );
}


export async function getServerSideProps() {
  try {
    const data = await axiosGet("get-homedata");
    return {
      props: { data },
    };
  } catch (error) {
    console.error("Error fetching data:", error);
    return {
      props: { data: {} },
    };
  }
}
